In [ ]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_images)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
train_labels.shape

(60000,)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
test_labels.shape

(10000,)

In [ ]:
test_labels.size

10000

In [ ]:
test_labels.data

In [ ]:
test_labels.dtype

dtype('uint8')

In [ ]:
test_labels.imag

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [ ]:
test_images.ndim

3

In [ ]:
test_labels.strides

(1,)

In [ ]:
len(test_images)

10000

In [ ]:
pip install numpy

In [ ]:
pip install pandas

In [ ]:
!pip install pandas

In [ ]:
!pip install -q pandas
import pandas

In [ ]:
!pip install -q numpy
import numpy

In [ ]:
!pip install -q matplotlib
import matplotlib

In [ ]:
import numpy as np


In [ ]:
!pip install numpy

In [ ]:
benimRandomDizim = np.random.randint(1,200,30)

In [ ]:
benimRandomDizim

array([151, 146, 123,   3, 188,  60, 193, 122,  20, 178,  74, 127,  67,
       178, 193,  71,  93, 132, 186, 168,  65, 198, 169, 170,  62, 152,
       169, 169,  60,  14])

In [ ]:
benimNumpyDizim = np.arange(1,30)

In [ ]:
benimNumpyDizim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
benimNumpyDizim.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
benimRandomDizim.reshape(6,5)

array([[151, 146, 123,   3, 188],
       [ 60, 193, 122,  20, 178],
       [ 74, 127,  67, 178, 193],
       [ 71,  93, 132, 186, 168],
       [ 65, 198, 169, 170,  62],
       [152, 169, 169,  60,  14]])

In [ ]:
benimNumpyDizim.max()

30

In [ ]:
benimRandomDizim.min()

3

In [ ]:
benimRandomDizim.argmin()

3

In [ ]:
benimRandomDizim.argmax()

21

In [ ]:
benimRandomDizim.max()

198

In [ ]:
import numpy as np


In [ ]:
benimRandomDizim= np.arange(1, 30)

In [ ]:
benimRandomDizim[3:9] = -1

In [ ]:
benimRandomDizim

array([ 1,  2,  3, -1, -1, -1, -1, -1, -1, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
benimListem= [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
ornekMatrixDizim = np.array(benimListem)

In [ ]:
ornekMatrixDizim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ornekMatrixDizim[1:2]

array([[4, 5, 6]])

In [ ]:
ornekMatrixDizim[1:,1]

array([5, 8])

In [ ]:
ornekMatrixDizim[0:,2]

array([3, 6, 9])

In [ ]:
ornekMatrixDizim[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
ornekMatrixDizim[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
yeniBirDizi= np.random.randint(1,100,20)

In [ ]:
yeniBirDizi

array([99, 16, 68, 61, 51, 79, 95, 46, 83, 13, 66, 28, 34, 67, 25, 20,  7,
       94, 16, 73])

In [ ]:
yeniBirDizi> 24

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False,  True])

In [ ]:
yeniBirDizi[3:7] = -1

In [ ]:
yeniBirDizi

array([99, 16, 68, -1, -1, -1, -1, 46, 83, 13, 66, 28, 34, 67, 25, 20,  7,
       94, 16, 73])

In [ ]:
sonucDizi = yeniBirDizi >24

In [ ]:
sonucDizi

array([ True, False,  True, False, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False,  True])

In [ ]:
yeniBirDizi[sonucDizi]

array([99, 68, 46, 83, 66, 28, 34, 67, 25, 94, 73])

In [ ]:
import pandas as pd

In [ ]:
benimSozlugum = {"Elif": 31, "Selçuk": 37, "Ali Evren": 1 }

In [ ]:
pd.Series(benimSozlugum)

Elif         31
Selçuk       37
Ali Evren     1
dtype: int64

In [ ]:
benimYaslarim = [31, 37, 1]

In [3]:
numpyDizi= np.array(benimYaslarim)

NameError: ignored

In [2]:
numpyDizi

NameError: ignored

In [ ]:
pd.Series(numpyDizi)

0    31
1    37
2     1
dtype: int64

In [ ]:
pd.Series(benimYaslarim)

0    31
1    37
2     1
dtype: int64

In [ ]:
import numpy as np

In [ ]:
sira= np.arange(1,4)

In [ ]:
pd.Series(benimYaslarim,sira)

1    31
2    37
3     1
dtype: int64

In [ ]:
yarismaSonucu1= pd.Series([10,20,30],["Elif", "Selçuk", "Ali Evren"])

In [ ]:
yarismaSonucu2= pd.Series([1,2,3],["Elif", "Selçuk", "Ali Evren"])

In [ ]:
yarismaSonucu1

Elif         10
Selçuk       20
Ali Evren    30
dtype: int64

In [ ]:
yarismaSonucu2

Elif         1
Selçuk       2
Ali Evren    3
dtype: int64

In [ ]:
sonSonuc= yarismaSonucu1 + yarismaSonucu2

In [ ]:
sonSonuc

Elif         11
Selçuk       22
Ali Evren    33
dtype: int64

In [ ]:
sonSonuc.max()

33

In [ ]:
data= np.random.randn(4,3)

In [ ]:
dataFrame = pd.DataFrame(data)

In [ ]:
dataFrame

0         1         2
0  1.296820  0.314104  1.243592
1 -1.686351 -0.381888  0.351092
2  0.555455 -0.806315 -0.085365
3 -0.702941  0.875006  2.799209

In [ ]:
yeniDataFrame = pd.DataFrame(data,index= ["Elif", "Selçuk", "Ali Evren", "Gül Kainat"], columns =["maas", "yas", "calisma saati"] )

In [ ]:
yeniDataFrame

maas       yas  calisma saati
Elif        1.296820  0.314104       1.243592
Selçuk     -1.686351 -0.381888       0.351092
Ali Evren   0.555455 -0.806315      -0.085365
Gül Kainat -0.702941  0.875006       2.799209

In [ ]:
yeniDataFrame["yas"]

Elif          0.693558
Selçuk       -0.179963
Ali Evren    -0.283514
Gül Kainat   -0.248298
Name: yas, dtype: float64

In [ ]:
yeniDataFrame["maas"]

Elif         -0.280733
Selçuk       -0.015499
Ali Evren    -1.151679
Gül Kainat    0.221477
Name: maas, dtype: float64

In [ ]:
yeniIndexList= ["EL","SEL","AL","GÜL"]

In [ ]:
yeniDataFrame["new_Index"] = yeniIndexList

In [ ]:
yeniDataFrame

maas       yas  calisma saati yeniIndex yeniIndexs new_Index
Elif       -0.539232 -1.221297       1.374450        EL         EL        EL
Selçuk     -1.528924 -1.377321       0.472829       SEL        SEL       SEL
Ali Evren   0.498717 -0.000785       1.356069        AL         AL        AL
Gül Kainat -1.007106 -0.091568       0.644459       GÜL        GÜL       GÜL

In [ ]:
yeniDataFrame.drop("yeniIndex", axis=1, inplace= True)

In [ ]:
yeniDataFrame.set_index("new_Index", inplace= True)

In [ ]:
yeniDataFrame

maas       yas  calisma saati yeniIndexs
new_Index                                              
EL        -0.539232 -1.221297       1.374450         EL
SEL       -1.528924 -1.377321       0.472829        SEL
AL         0.498717 -0.000785       1.356069         AL
GÜL       -1.007106 -0.091568       0.644459        GÜL

In [ ]:
yeniDataFrame.drop("yeniIndexs", axis=1, inplace= True)

In [ ]:
yeniDataFrame

maas       yas  calisma saati
new_Index                                   
EL        -0.539232 -1.221297       1.374450
SEL       -1.528924 -1.377321       0.472829
AL         0.498717 -0.000785       1.356069
GÜL       -1.007106 -0.091568       0.644459

In [ ]:
yeniDataFrame.loc["EL"]

maas            -0.539232
yas             -1.221297
calisma saati    1.374450
Name: EL, dtype: float64

In [ ]:
yeniDataFrame["yas"]

new_Index
EL    -1.221297
SEL   -1.377321
AL    -0.000785
GÜL   -0.091568
Name: yas, dtype: float64

In [ ]:
ilkIndex= ["Ural","Ural","Ural","Ural","Ozgun","Ozgun","Ozgun"]

In [ ]:
icIndex=["EL","SEL","AL","GÜL","SED","YUR","MEH"]

In [ ]:
birlesikIndex= list(zip(ilkIndex,icIndex))

In [ ]:
birlesikIndex

[('Ural', 'EL'),
 ('Ural', 'SEL'),
 ('Ural', 'AL'),
 ('Ural', 'GÜL'),
 ('Ozgun', 'SED'),
 ('Ozgun', 'YUR'),
 ('Ozgun', 'MEH')]

In [ ]:
birlesikIndex = pd.MultiIndex.from_tuples(birlesikIndex)

In [ ]:
birlesikIndex

MultiIndex([( 'Ural',  'EL'),
            ( 'Ural', 'SEL'),
            ( 'Ural',  'AL'),
            ( 'Ural', 'GÜL'),
            ('Ozgun', 'SED'),
            ('Ozgun', 'YUR'),
            ('Ozgun', 'MEH')],
           )

In [ ]:
type(birlesikIndex)

pandas.core.indexes.multi.MultiIndex

In [ ]:
 benimListem= [[31,"K"],[37,"E"],[1,"E"],[0,"K"],[60,"E"],[58,"K"],[24,"E"]]

In [ ]:
aileDizisi = pd.DataFrame(benimListem, index= birlesikIndex, columns= ["AGE", "GENDER"])

In [ ]:
aileDizisi

AGE GENDER
Ural  EL    31      K
      SEL   37      E
      AL     1      E
      GÜL    0      K
Ozgun SED   60      E
      YUR   58      K
      MEH   24      E

In [ ]:
aileDizisi.index.names= ["INDEX","USER_NAME"]

In [ ]:
aileDizisi

AGE GENDER
INDEX USER_NAME            
Ural  EL          31      K
      SEL         37      E
      AL           1      E
      GÜL          0      K
Ozgun SED         60      E
      YUR         58      K
      MEH         24      E

In [ ]:
sozluk_Verisi= {"İstanbul" : [30, 29, np.nan, 28, 22, 20, 24], "Ankara": [20, np.nan, 25, 26, 22, 20, 19], "İzmir": [20, np.nan, 23, 26, np.nan, 20, 28]}

In [ ]:
havaDurumuDataFrame= pd.DataFrame(sozluk_Verisi)

In [ ]:
havaDurumuDataFrame

İstanbul  Ankara  İzmir
0      30.0    20.0   20.0
1      29.0     NaN    NaN
2       NaN    25.0   23.0
3      28.0    26.0   26.0
4      22.0    22.0    NaN
5      20.0    20.0   20.0
6      24.0    19.0   28.0

In [ ]:
index= ["Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"]

In [ ]:
havaDurumuDataFrame["DAYS"] = index


In [ ]:
havaDurumuDataFrame.set_index("DAYS", inplace=True)

In [ ]:
havaDurumuDataFrame.dropna(axis = 1, thresh=2)

İstanbul  Ankara  İzmir
DAYS                              
Pazartesi      30.0    20.0   20.0
Salı           29.0     NaN    NaN
Çarşamba        NaN    25.0   23.0
Perşembe       28.0    26.0   26.0
Cuma           22.0    22.0    NaN
Cumartesi      20.0    20.0   20.0
Pazar          24.0    19.0   28.0

In [ ]:
havaDurumuDataFrame.drop

İstanbul  Ankara  İzmir
DAYS                              
Pazartesi      30.0    20.0   20.0
Salı           29.0     NaN    NaN
Çarşamba        NaN    25.0   23.0
Perşembe       28.0    26.0   26.0
Cuma           22.0    22.0    NaN
Cumartesi      20.0    20.0   20.0
Pazar          24.0    19.0   28.0

In [ ]:
import numpy as np


In [ ]:
import pandas as pd


In [ ]:
havaDurumuDataFrame.fillna(20)

İstanbul  Ankara  İzmir
DAYS                              
Pazartesi      30.0    20.0   20.0
Salı           29.0    20.0   20.0
Çarşamba       20.0    25.0   23.0
Perşembe       28.0    26.0   26.0
Cuma           22.0    22.0   20.0
Cumartesi      20.0    20.0   20.0
Pazar          24.0    19.0   28.0

In [ ]:
havaDurumuDataFrame.dropna(thresh=2, axis=0)

İstanbul  Ankara  İzmir
DAYS                              
Pazartesi      30.0    20.0   20.0
Çarşamba        NaN    25.0   23.0
Perşembe       28.0    26.0   26.0
Cuma           22.0    22.0    NaN
Cumartesi      20.0    20.0   20.0
Pazar          24.0    19.0   28.0

In [ ]:
havaDurumuDataFrame.dropna(thresh=2, axis =1)

İstanbul  Ankara  İzmir
DAYS                              
Pazartesi      30.0    20.0   20.0
Salı           29.0     NaN    NaN
Çarşamba        NaN    25.0   23.0
Perşembe       28.0    26.0   26.0
Cuma           22.0    22.0    NaN
Cumartesi      20.0    20.0   20.0
Pazar          24.0    19.0   28.0

In [ ]:
persons= {"Departman":["Bilgi Teknolojileri", "Bilgi Teknolojileri","Hukuk","Hukuk","Muhasebe","Muhasebe", "Satış", "Pazarlama"],
          "Calisan": ["Elif", "Elif", "Selçuk", "Ali Evren", "Gül Kainat","Mehmet Ertuğrul", "Yurdagül", "Sedat"],
          "Maas": [5000, 1000,2000,3000,1000,5000,4000,4000]}

In [ ]:
persons

{'Departman': ['Bilgi Teknolojileri',
  'İnsan Kaynakları',
  'Hukuk',
  'Muhasebe',
  'Finans',
  'Satış',
  'Pazarlama'],
 'Calisan': ['Elif',
  'Selçuk',
  'Ali Evren',
  'Gül Kainat',
  'Mehmet Ertuğrul',
  'Yurdagül',
  'Sedat'],
 'Maas': [1000, 2000, 3000, 1000, 5000, 4000, 4000]}

In [ ]:
calisanDataFreame = pd.DataFrame(persons)

In [ ]:
calisanDataFreame

Departman          Calisan  Maas
0  Bilgi Teknolojileri             Elif  1000
1                Hukuk           Selçuk  2000
2                Hukuk        Ali Evren  3000
3             Muhasebe       Gül Kainat  1000
4             Muhasebe  Mehmet Ertuğrul  5000
5                Satış         Yurdagül  4000
6            Pazarlama            Sedat  4000

In [ ]:
groupByObjesi = calisanDataFreame.groupby("Departman")

In [ ]:
groupByObjesi.count()

Calisan  Maas
Departman                         
Bilgi Teknolojileri        1     1
Hukuk                      2     2
Muhasebe                   2     2
Pazarlama                  1     1
Satış                      1     1

In [ ]:
calisanTablo = groupByObjesi.describe()

In [ ]:
calisanTablo

Maas                                               \
                    count    mean          std     min     25%     50%   
Departman                                                                
Bilgi Teknolojileri   1.0  1000.0          NaN  1000.0  1000.0  1000.0   
Hukuk                 2.0  2500.0   707.106781  2000.0  2250.0  2500.0   
Muhasebe              2.0  3000.0  2828.427125  1000.0  2000.0  3000.0   
Pazarlama             1.0  4000.0          NaN  4000.0  4000.0  4000.0   
Satış                 1.0  4000.0          NaN  4000.0  4000.0  4000.0   

                                     
                        75%     max  
Departman                            
Bilgi Teknolojileri  1000.0  1000.0  
Hukuk                2750.0  3000.0  
Muhasebe             4000.0  5000.0  
Pazarlama            4000.0  4000.0  
Satış                4000.0  4000.0

In [ ]:
calisanDataFreame.value_counts()

Departman            Calisan          Maas
Bilgi Teknolojileri  Elif             1000    1
Hukuk                Ali Evren        3000    1
                     Selçuk           2000    1
Muhasebe             Gül Kainat       1000    1
                     Mehmet Ertuğrul  5000    1
Pazarlama            Sedat            4000    1
Satış                Yurdagül         4000    1
dtype: int64

In [ ]:
calisanDataFreame["Departman"].value_counts()

Hukuk                  2
Muhasebe               2
Bilgi Teknolojileri    1
Satış                  1
Pazarlama              1
Name: Departman, dtype: int64

In [ ]:
calisanDataFreame["Departman"].unique()

array(['Bilgi Teknolojileri', 'Hukuk', 'Muhasebe', 'Satış', 'Pazarlama'],
      dtype=object)

In [ ]:
calisanDataFreame["Departman"].nunique()

5

In [ ]:
def bruttenNete(maas):
  return maas * 0.66

In [ ]:
calisanBruttenNete = calisanDataFreame["Maas"].apply(bruttenNete)

In [ ]:
calisanDataFreame["Maas"] = calisanBruttenNete

In [ ]:
calisanDataFreame

Departman          Calisan    Maas
0  Bilgi Teknolojileri             Elif   660.0
1                Hukuk           Selçuk  1320.0
2                Hukuk        Ali Evren  1980.0
3             Muhasebe       Gül Kainat   660.0
4             Muhasebe  Mehmet Ertuğrul  3300.0
5                Satış         Yurdagül  2640.0
6            Pazarlama            Sedat  2640.0

In [ ]:
calisanDataFreame

Departman          Calisan    Maas
0  Bilgi Teknolojileri             Elif   660.0
1                Hukuk           Selçuk  1320.0
2                Hukuk        Ali Evren  1980.0
3             Muhasebe       Gül Kainat   660.0
4             Muhasebe  Mehmet Ertuğrul  3300.0
5                Satış         Yurdagül  2640.0
6            Pazarlama            Sedat  2640.0

In [ ]:
calisanDataFreame.isnull()

Departman  Calisan   Maas
0      False    False  False
1      False    False  False
2      False    False  False
3      False    False  False
4      False    False  False
5      False    False  False
6      False    False  False

In [ ]:
calisanDataFreame.pivot_table(values= ["Maas"], index = ["Departman", "Calisan"], aggfunc=np.sum )

Maas
Departman           Calisan              
Bilgi Teknolojileri Elif             6000
Hukuk               Ali Evren        3000
                    Selçuk           2000
Muhasebe            Gül Kainat       1000
                    Mehmet Ertuğrul  5000
Pazarlama           Sedat            4000
Satış               Yurdagül         4000

In [ ]:
calisanDataFreame.to_excel("persons.xlsx")

In [ ]:
pd.read_excel("persons.xlsx")

Unnamed: 0            Departman          Calisan  Maas
0           0  Bilgi Teknolojileri             Elif  5000
1           1  Bilgi Teknolojileri             Elif  1000
2           2                Hukuk           Selçuk  2000
3           3                Hukuk        Ali Evren  3000
4           4             Muhasebe       Gül Kainat  1000
5           5             Muhasebe  Mehmet Ertuğrul  5000
6           6                Satış         Yurdagül  4000
7           7            Pazarlama            Sedat  4000

In [ ]:
 !pip install matplotlib

In [ ]:
import numpy as